#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XAXIDMA_NUM_INSTANCES 1

/* Definitions for peripheral AXI_ETHERNET_0_DMA */
#define XPAR_AXI_ETHERNET_0_DMA_COMPATIBLE "xlnx,eth-dma"
#define XPAR_AXI_ETHERNET_0_DMA_BASEADDR 0x41e00000
#define XPAR_AXI_ETHERNET_0_DMA_HIGHADDR 0x41e0ffff
#define XPAR_AXI_ETHERNET_0_DMA_SG_INCLUDE_STSCNTRL_STRM 0x1
#define XPAR_AXI_ETHERNET_0_DMA_INCLUDE_MM2S 0x1
#define XPAR_AXI_ETHERNET_0_DMA_INCLUDE_MM2S_DRE 0x1
#define XPAR_AXI_ETHERNET_0_DMA_MM2S_DATA_WIDTH 0x20
#define XPAR_AXI_ETHERNET_0_DMA_INCLUDE_S2MM 0x1
#define XPAR_AXI_ETHERNET_0_DMA_INCLUDE_S2MM_DRE 0x1
#define XPAR_AXI_ETHERNET_0_DMA_S2MM_DATA_WIDTH 0x20
#define XPAR_AXI_ETHERNET_0_DMA_NUM_MM2S_CHANNELS 0x1
#define XPAR_AXI_ETHERNET_0_DMA_NUM_S2MM_CHANNELS 0x1
#define XPAR_AXI_ETHERNET_0_DMA_MM2S_BURST_SIZE 0x10
#define XPAR_AXI_ETHERNET_0_DMA_S2MM_BURST_SIZE 0x10
#define XPAR_AXI_ETHERNET_0_DMA_MICRO_DMA 0x0
#define XPAR_AXI_ETHERNET_0_DMA_ADDRWIDTH 0x20
#define XPAR_AXI_ETHERNET_0_DMA_SG_LENGTH_WIDTH 0x10
#define XPAR_AXI_ETHERNET_0_DMA_INTERRUPTS 0x2001
#define XPAR_AXI_ETHERNET_0_DMA_INTERRUPTS_1 0x2002
#define XPAR_FABRIC_AXI_ETHERNET_0_DMA_INTR 1
#define XPAR_FABRIC_AXI_ETHERNET_0_DMA_INTR_1 2
#define XPAR_AXI_ETHERNET_0_DMA_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_ETHERNET_0_DMA */
#define XPAR_XAXIDMA_0_BASEADDR 0x41e00000
#define XPAR_FABRIC_XAXIDMA_0_INTR 1
#define XPAR_XAXIDMA_0_HIGHADDR 0x41e0ffff
#define XPAR_XAXIDMA_0_ADDRWIDTH 0x20
#define XPAR_XAXIDMA_0_COMPATIBLE "xlnx,eth-dma"
#define XPAR_XAXIDMA_0_INCLUDE_MM2S 0x1
#define XPAR_XAXIDMA_0_INCLUDE_MM2S_DRE 0x1
#define XPAR_XAXIDMA_0_INCLUDE_S2MM 0x1
#define XPAR_XAXIDMA_0_INCLUDE_S2MM_DRE 0x1
#define XPAR_XAXIDMA_0_INTERRUPTS 0x2001
#define XPAR_XAXIDMA_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XAXIDMA_0_MM2S_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_0_MM2S_BURST_SIZE 0x10
#define XPAR_XAXIDMA_0_MICRO_DMA 0x0
#define XPAR_XAXIDMA_0_NUM_MM2S_CHANNELS 0x1
#define XPAR_XAXIDMA_0_NUM_S2MM_CHANNELS 0x1
#define XPAR_XAXIDMA_0_SG_INCLUDE_STSCNTRL_STRM 0x1
#define XPAR_XAXIDMA_0_S2MM_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_0_S2MM_BURST_SIZE 0x10
#define XPAR_XAXIDMA_0_SG_LENGTH_WIDTH 0x10

#define XPAR_XAXIETHERNET_NUM_INSTANCES 1

/* Definitions for peripheral AXI_ETHERNET_0 */
#define XPAR_AXI_ETHERNET_0_COMPATIBLE "xlnx,axi-ethernet-8.0"
#define XPAR_AXI_ETHERNET_0_BASEADDR 0x40c00000
#define XPAR_AXI_ETHERNET_0_HIGHADDR 0x40c3ffff
#define XPAR_AXI_ETHERNET_0_TXCSUM 0x0
#define XPAR_AXI_ETHERNET_0_RXCSUM 0x0
#define XPAR_AXI_ETHERNET_0_PHY_MODE "rgmii"
#define XPAR_AXI_ETHERNET_0_STATISTICS_COUNTERS 0x1
#define XPAR_AXI_ETHERNET_0_SPEED_1_2P5 0x3e8
#define XPAR_AXI_ETHERNET_0_NUMBER_OF_TABLE_ENTRIES 0x0
#define XPAR_AXI_ETHERNET_0_PHYADDR 0x1
#define XPAR_AXI_ETHERNET_0_INTERRUPTS 0x2004
#define XPAR_AXI_ETHERNET_0_INTERRUPTS_1 0x3
#define XPAR_FABRIC_AXI_ETHERNET_0_INTR 4
#define XPAR_FABRIC_AXI_ETHERNET_0_INTR_1 3
#define XPAR_AXI_ETHERNET_0_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_ETHERNET_0_AXISTREAM_CONNECTED 0x41e00002

/* Canonical definitions for peripheral AXI_ETHERNET_0 */
#define XPAR_XAXIETHERNET_0_BASEADDR 0x40c00000
#define XPAR_FABRIC_XAXIETHERNET_0_INTR 4
#define XPAR_XAXIETHERNET_0_HIGHADDR 0x40c3ffff
#define XPAR_XAXIETHERNET_0_AXISTREAM_CONNECTED 0x41e00002
#define XPAR_XAXIETHERNET_0_COMPATIBLE "xlnx,axi-ethernet-8.0"
#define XPAR_XAXIETHERNET_0_INTERRUPTS 0x2004
#define XPAR_XAXIETHERNET_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XAXIETHERNET_0_NUMBER_OF_TABLE_ENTRIES 0x0
#define XPAR_XAXIETHERNET_0_PHY_MODE "rgmii"
#define XPAR_XAXIETHERNET_0_PHYADDR 0x1
#define XPAR_XAXIETHERNET_0_RXCSUM 0x0
#define XPAR_XAXIETHERNET_0_STATISTICS_COUNTERS 0x1
#define XPAR_XAXIETHERNET_0_SPEED_1_2P5 0x3e8
#define XPAR_XAXIETHERNET_0_TXCSUM 0x0

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x1ffff
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 0x20
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_XBRAM_0_BASEADDR 0x0
#define XPAR_XBRAM_0_HIGHADDR 0x1ffff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x2

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC_0 */
#define XPAR_MICROBLAZE_0_AXI_INTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_0_AXI_INTC_0_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_0_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_0_AXI_INTC_0_KIND_OF_INTR 0x8
#define XPAR_MICROBLAZE_0_AXI_INTC_0_IS_FAST 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_0_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_0_AXI_INTC_0_NUM_INTR_INPUTS 0x5
#define XPAR_MICROBLAZE_0_AXI_INTC_0_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_0_AXI_INTC_0_NUM_SW_INTR 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_0_HAS_IVR 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_0_HAS_CIE 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_0_HAS_SIE 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_0_HAS_IPR 0x1

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC_0 */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_HAS_IVR 0x1
#define XPAR_XINTC_0_HAS_CIE 0x1
#define XPAR_XINTC_0_HAS_SIE 0x1
#define XPAR_XINTC_0_HAS_IPR 0x1
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_KIND_OF_INTR 0x8
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x5
#define XPAR_XINTC_0_NUM_SW_INTR 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_0_BASEADDR 0x41c00000
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41c0ffff
#define XPAR_AXI_TIMER_0_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_AXI_TIMER_0_INTERRUPTS 0x2000
#define XPAR_FABRIC_AXI_TIMER_0_INTR 0
#define XPAR_AXI_TIMER_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x41c00000
#define XPAR_FABRIC_XTMRCTR_0_INTR 0
#define XPAR_XTMRCTR_0_HIGHADDR 0x41c0ffff
#define XPAR_XTMRCTR_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY 0x5f5e100
#define XPAR_XTMRCTR_0_INTERRUPTS 0x2000
#define XPAR_XTMRCTR_0_INTERRUPT_PARENT 0x41200001

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x2580
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x2580
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral TOKENIZER_AXI_LITE_0 */
#define XPAR_TOKENIZER_AXI_LITE_0_BASEADDR 0x44a00000
#define XPAR_TOKENIZER_AXI_LITE_0_HIGHADDR 0x44a00fff

/*  BOARD definition */
#define XPS_BOARD_NEXYS_VIDEO

#define XPAR_MIG_0_BASEADDRESS 0x80000000
#define XPAR_MIG_0_HIGHADDRESS 0x9fffffff
#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x1ffff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_EXCEPTIONS_IN_DELAY_SLOTS 1
#define XPAR_MICROBLAZE_FREQ 100000000
#define XPAR_MICROBLAZE_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_D_CACHE_SIZE 32768
#define XPAR_MICROBLAZE_I_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_I_CACHE_SIZE 32768
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 14
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 32768
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 14
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 32768
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_TIMEBASE_FREQUENCY 100000000
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 16
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER2 0
#define XPAR_MICROBLAZE_RESET_MSR 0
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_USE_BARREL 0
#define XPAR_MICROBLAZE_USE_DCACHE 1
#define XPAR_MICROBLAZE_USE_DIV 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 0
#define XPAR_MICROBLAZE_USE_ICACHE 1
#define XPAR_MICROBLAZE_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_D_CACHE_BASEADDR 2147483648
#define XPAR_MICROBLAZE_D_CACHE_HIGHADDR 2684354559
#define XPAR_MICROBLAZE_I_CACHE_BASEADDR 2147483648
#define XPAR_MICROBLAZE_I_CACHE_HIGHADDR 2684354559
#define XPAR_MICROBLAZE_REG 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_DDR_RESERVE_SA 0

#define XPAR_MICROBLAZE_ADDR_SIZE 32

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a200t"

#endif  /* end of protection macro */